In [1]:
import pandas as pd

In [2]:
scores={
    "name":['jamal','kamal','aziz'],
    "city":['Boukan','sanadaj','maraghe'],
    "grade":[75,60,80]
}

In [3]:
df=pd.DataFrame(scores)

In [7]:
df['name']

0    jamal
1    kamal
2     aziz
Name: name, dtype: object

In [8]:
df['name_city']=df['name']+'_'+df['city']

In [9]:
df

    name     city  grade      name_city
0  jamal   Boukan     75   jamal_Boukan
1  kamal  sanadaj     60  kamal_sanadaj
2   aziz  maraghe     80   aziz_maraghe

In [12]:
df[df['grade']>60]

    name     city  grade     name_city
0  jamal   Boukan     75  jamal_Boukan
2   aziz  maraghe     80  aziz_maraghe

In [103]:
iris=pd.read_csv('D:\project\dataset\CSV_Files\iris.csv')

In [104]:
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0          5.10         3.50          1.40         0.20  Setosa
1          4.90         3.00          1.40         0.20  Setosa
2          4.70         3.20          1.30         0.20  Setosa
3          4.60         3.10          1.50         0.20  Setosa
4          5.00         3.60          1.40         0.20  Setosa

In [107]:
df1=iris.groupby('variety').sum()
df1

            sepal.length  sepal.width  petal.length  petal.width
variety
Setosa            250.30       171.40         73.10        12.30
Versicolor        296.80       138.50        213.00        66.30
Virginica         329.40       148.70        277.60       101.30

In [108]:
df2=iris.groupby('variety').agg({'sepal.length':['mean','max','min'],'petal.width':['count','min']})
df2

           sepal.length           petal.width
                   mean  max  min       count  min
variety
Setosa             5.01 5.80 4.30          50 0.10
Versicolor         5.94 7.00 4.90          50 1.00
Virginica          6.59 7.90 4.90          50 1.40

In [16]:
iris.shape

(150, 5)

In [19]:
iris.tail(3)

     sepal.length  sepal.width  petal.length  petal.width    variety
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [20]:
iris.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [21]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [27]:
iris.loc[:9,'variety']

0    Setosa
1    Setosa
2    Setosa
3    Setosa
4    Setosa
5    Setosa
6    Setosa
7    Setosa
8    Setosa
9    Setosa
Name: variety, dtype: object

In [28]:
iris.iloc[3,2]

1.5

In [100]:
iris.to_csv('D:\project\dataset\CSV_Files\IRIS_generated', index=False)

In [101]:
iris2=pd.read_csv('D:\project\dataset\CSV_Files\IRIS_generated')

In [102]:
iris2

,h t g n e l _ l a p e s,h t d i w _ l a p e s,h t g n e l _ l a t e p,h t d i w _ l a t e p,y t e i r a v
0,5.10,3.50,1.40,0.20,Setosa
1,4.90,3.00,1.40,0.20,Setosa
2,4.70,3.20,1.30,0.20,Setosa
3,4.60,3.10,1.50,0.20,Setosa
4,5.00,3.60,1.40,0.20,Setosa
...,...,...,...,...,...
145,6.70,3.00,5.20,2.30,Virginica
146,6.30,2.50,5.00,1.90,Virginica
147,6.50,3.00,5.20,2.00,Virginica
148,6.20,3.40,5.40,2.30,Virginica
149,5.90,3.00,5.10,1.80,Virginica

In [41]:
pd.set_option("display.max_rows", 10)
iris

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [98]:
pd.options.display.float_format='{:,.2f}'.format

In [99]:
iris

,h t g n e l _ l a p e s,h t d i w _ l a p e s,h t g n e l _ l a t e p,h t d i w _ l a t e p,y t e i r a v
0,5.10,3.50,1.40,0.20,Setosa
1,4.90,3.00,1.40,0.20,Setosa
2,4.70,3.20,1.30,0.20,Setosa
3,4.60,3.10,1.50,0.20,Setosa
4,5.00,3.60,1.40,0.20,Setosa
...,...,...,...,...,...
145,6.70,3.00,5.20,2.30,Virginica
146,6.30,2.50,5.00,1.90,Virginica
147,6.50,3.00,5.20,2.00,Virginica
148,6.20,3.40,5.40,2.30,Virginica
149,5.90,3.00,5.10,1.80,Virginica

In [58]:
iris.columns=iris.columns.str.replace('.','_')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_15748\975520652.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  iris.columns=iris.columns.str.replace('.','_')

In [59]:
iris

     sepal_length  sepal_width  petal_length  petal_width    variety
0               5            4             1            0     Setosa
1               5            3             1            0     Setosa
2               5            3             1            0     Setosa
3               5            3             2            0     Setosa
4               5            4             1            0     Setosa
..            ...          ...           ...          ...        ...
145             7            3             5            2  Virginica
146             6            2             5            2  Virginica
147             6            3             5            2  Virginica
148             6            3             5            2  Virginica
149             6            3             5            2  Virginica

[150 rows x 5 columns]

In [61]:
iris.columns=iris.columns.str.lower()
iris

     sepal_length  sepal_width  petal_length  petal_width    variety
0               5            4             1            0     Setosa
1               5            3             1            0     Setosa
2               5            3             1            0     Setosa
3               5            3             2            0     Setosa
4               5            4             1            0     Setosa
..            ...          ...           ...          ...        ...
145             7            3             5            2  Virginica
146             6            2             5            2  Virginica
147             6            3             5            2  Virginica
148             6            3             5            2  Virginica
149             6            3             5            2  Virginica

[150 rows x 5 columns]

In [62]:
iris.columns=iris.columns.str.upper()
iris

     SEPAL_LENGTH  SEPAL_WIDTH  PETAL_LENGTH  PETAL_WIDTH    VARIETY
0               5            4             1            0     Setosa
1               5            3             1            0     Setosa
2               5            3             1            0     Setosa
3               5            3             2            0     Setosa
4               5            4             1            0     Setosa
..            ...          ...           ...          ...        ...
145             7            3             5            2  Virginica
146             6            2             5            2  Virginica
147             6            3             5            2  Virginica
148             6            3             5            2  Virginica
149             6            3             5            2  Virginica

[150 rows x 5 columns]

In [65]:
iris.columns.str.split('_')

Index([['SEPAL', 'LENGTH'],  ['SEPAL', 'WIDTH'], ['PETAL', 'LENGTH'],
        ['PETAL', 'WIDTH'],         ['VARIETY']],
      dtype='object')

In [66]:
iris.columns=iris.columns.str.lower()

In [67]:
iris.columns=pd.Series(i[::-1] for i in iris.columns)

In [68]:
iris.columns

Index(['htgnel_lapes', 'htdiw_lapes', 'htgnel_latep', 'htdiw_latep',
       'yteirav'],
      dtype='object')

In [69]:
iris.columns=[' '.join(i) for i in iris.columns]

In [70]:
iris.columns

Index(['h t g n e l _ l a p e s', 'h t d i w _ l a p e s',
       'h t g n e l _ l a t e p', 'h t d i w _ l a t e p', 'y t e i r a v'],
      dtype='object')

In [73]:
iris.columns=iris.columns.str.strip()

In [74]:
iris.columns

Index(['h t g n e l _ l a p e s', 'h t d i w _ l a p e s',
       'h t g n e l _ l a t e p', 'h t d i w _ l a t e p', 'y t e i r a v'],
      dtype='object')

In [75]:
# Time Series

In [85]:
datarange=pd.period_range('1/1/2020', freq='30d', periods=4)

In [86]:
date_df=pd.DataFrame(data=datarange, columns=['sample_date'])
date_df

  sample_date
0  2020-01-01
1  2020-01-31
2  2020-03-01
3  2020-03-31

In [87]:
date_df['date_difference']=date_df['sample_date'].diff(periods=1)
date_df

  sample_date date_difference
0  2020-01-01             NaT
1  2020-01-31     <30 * Days>
2  2020-03-01     <30 * Days>
3  2020-03-31     <30 * Days>

In [88]:
date_df['first of month']=date_df['sample_date'].values.astype('datetime64[M]')
date_df

  sample_date date_difference first of month
0  2020-01-01             NaT     2020-01-01
1  2020-01-31     <30 * Days>     2020-01-01
2  2020-03-01     <30 * Days>     2020-03-01
3  2020-03-31     <30 * Days>     2020-03-01

In [89]:
date_df.dtypes

sample_date           period[30D]
date_difference            object
first of month     datetime64[ns]
dtype: object

In [90]:
date_df['Time_Stamped_date']=date_df['sample_date'].dt.to_timestamp()
date_df

  sample_date date_difference first of month Time_Stamped_date
0  2020-01-01             NaT     2020-01-01        2020-01-01
1  2020-01-31     <30 * Days>     2020-01-01        2020-01-31
2  2020-03-01     <30 * Days>     2020-03-01        2020-03-01
3  2020-03-31     <30 * Days>     2020-03-01        2020-03-31

In [94]:
date_df.dtypes

sample_date             period[30D]
date_difference              object
first of month       datetime64[ns]
Time_Stamped_date    datetime64[ns]
dtype: object

In [95]:
date_df['Time_Stamped_date']-date_df['first of month']

0    0 days
1   30 days
2    0 days
3   30 days
dtype: timedelta64[ns]

In [96]:
date_df['Time_Stamped_date'].dt.day_name()

0    Wednesday
1       Friday
2       Sunday
3      Tuesday
Name: Time_Stamped_date, dtype: object

In [97]:
iris

,h t g n e l _ l a p e s,h t d i w _ l a p e s,h t g n e l _ l a t e p,h t d i w _ l a t e p,y t e i r a v
0,5,4,1,0,Setosa
1,5,3,1,0,Setosa
2,5,3,1,0,Setosa
3,5,3,2,0,Setosa
4,5,4,1,0,Setosa
...,...,...,...,...,...
145,7,3,5,2,Virginica
146,6,2,5,2,Virginica
147,6,3,5,2,Virginica
148,6,3,5,2,Virginica
149,6,3,5,2,Virginica